### ISSUE TITLE
Add caching so that files don’t need to be rebuilt unless there are changes

### ISSUE THREAD

**Issue by mjreich** [nxus/clientjs#2]

**Comment by loppear** [comment]
Presume you mean on startup (watchify should be handling dev-time rebuilding in a minimum fashion). The result output file is "cached" if its already been generated (though we're generally not checking these into source control), but because we can't know all the files that might need to be checked for newer timestamps than the cached output unless we run the browserify process, I'm not sure how we can do this.

**Comment by mjreich** [comment]
I think this is because of some weirdness with watchify - some rebuilds took < 0.5 seconds, some took 8 seconds for a complete recompile. Haven’t run into this recently.  

Happy to close.

**Comment by loppear** [comment]
Ok, yeah, I think there's some weirdness with watchify + core restarts, will pay attention and file a separate issue when I see it again.
